html+css pages
quicksilver32/Rick-and-Morty pull request #1
Opened 2022-03-02 15:58 UTC by quicksilver32

2022-03-04 10:50 UTC, alserz1 requested changes

2022-03-04 10:50 UTC, alserz1 commented on public/css/index.css
> +    grid-template-columns: 50% 50%;
с процентами в гридах нужно работать очень аккуратно. Ширина этого элемента получится 100% родителя+20px промежутка.

Собрал небольшую демку, на которой это видно без девтулзов: https://codesandbox.io/s/crazy-sinoussi-qqcgsj?file=/src/styles.css

2022-03-04 10:50 UTC, alserz1 commented on public/character.html
> +      href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
скорее всего, тут опечатка в пути, сейчас эта css-ка не загрузится. Но вообще я не вижу использований font-awesome (искал по всему проекту "fa-"), так что вообще нет смысла её грузить

2022-03-04 10:50 UTC, alserz1 commented on public/character.html
> +            <img class="logo-img" src="images/logo2.png" alt="logo" />
у каждой картинки лучше задавать размеры, чтобы браузер мог зарезервировать под неё место до окончания её загрузки

2022-03-04 10:50 UTC, alserz1 commented on public/characters.html
> +          <p class="filter-value">alive</p>
Все эти элементы являются кнопками, так что не стоит использовать для них тег p.

2022-03-04 10:50 UTC, alserz1 commented on public/characters.html
> +          <p class="filter-value">Mythological Cre...</p>
Думаю, тут должно быть Mythological Creatures) Обрезание текста в подавляющем большинстве случаев удобнее делать на стороне CSS. Также, не стоит забывать про то, что должна быть возможность просмотреть текст целиком, хотя бы через всплывающую подсказку. Даже это не лучший выход, потому что всплывающие подсказки не работают на тач-устройствах, поэтому обрезания текста на кнопках вообще стараются избегать.

2022-03-04 10:50 UTC, alserz1 commented on public/css/cards.css
> +    grid-column-start: 1;
во многих местах указано где конкретно в гриде нужно располагать элемент, можно этого не делать. Конкретно в этом проекте, многие свойства говорят элементу встать туда, куда его бы и так поставил браузер.

2022-03-04 10:50 UTC, alserz1 commented on public/css/cards.css
> +.filter-selected, .filter-value:hover {
кликабельные элементы по ховеру обычно имеют cursor: pointer, здесь его не хватает.

2022-03-04 10:50 UTC, alserz1 commented on public/css/cards.css
> +    outline: none;
не стоит совсем отключать обводку, она реально полезна. Если уж не нравится стандартная браузерная обводка, то нужно предоставлять свою

2022-03-04 10:50 UTC, alserz1 commented on public/css/cards.css
> +    transition: opacity 0.5s ease 0s;
зачем этот transition? У картинок ничего не меняется, анимация не срабатывает. У меня возникает ощущение, что многие стили взяты у создателей API. Я не против копирования чужого кода, но всегда нужно разбираться зачем он вообще написан

2022-03-04 10:50 UTC, alserz1 commented on public/characters.html
> +          <svg
лучше не вставлять svg в HTML, если он статический. Если сохранить его как отдельный файл и использовать через CSS, то браузер сможет закешировать его и не грузить на каждой странице

2022-03-04 10:50 UTC, alserz1 commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
эту штуку лучше не удалять, она телефонам нужна

2022-03-04 10:50 UTC, alserz1 commented on public/index.html
> -    <noscript>You need to enable JavaScript to run this app.</noscript>
noscript тоже лучше не трогать, даже если там дежурная фраза. Всё же лучше, чем пустота

2022-03-04 10:57 UTC, alserz1 commented
Оставил комментарии в коде. У меня есть большие подозрения, что многие стили скопированы с rickandmortyapi, поэтому для получения зачёта придётся разобраться и прибраться в коде. Возможно, при повторном ревью я позадаю вопросы в духе "почему здесь написано именно так?"

2022-03-04 11:23 UTC, quicksilver32 commented on public/character.html
> +            <img class="logo-img" src="images/logo2.png" alt="logo" />
А то что в css прописано max-width этого недостаточно? Или надо именно через свойство width и height в самом теге прописывать?

2022-03-04 11:45 UTC, alserz1 commented on public/character.html
> +            <img class="logo-img" src="images/logo2.png" alt="logo" />
Проблема max-width в том, что браузеру нужно загрузить CSS, распарсить его, построить CSSOM и применить его. С картинкой примерно та же история - пока она не загружена - браузер не знает её размеров. Это может привести к тому, что контент на странице сдвинется после загрузки

2022-03-04 14:18 UTC, quicksilver32 commented
> У меня есть большие подозрения, что многие стили скопированы с rickandmortyapi.
Был позаимствован только дизайн карточек, так как он мне показался достаточно удачным и информативным. Со стилями в них не до конца всё поправила, действительно. Спасибо за разъяснение)

2022-03-05 06:34 UTC, alserz1 commented on package.json
> +    "prettier": "^2.5.1",
prettier это крутая штука, советую ещё пре-коммит хук, чтобы вообще не думать про форматирование: https://prettier.io/docs/en/precommit.html

2022-03-05 06:34 UTC, alserz1 commented on public/characters.html
> +            <button class="filter__value">alive</button>
у `button` есть небольшой подводный камень, у них `type="submit"` по умолчанию. Если кнопка окажется в `form`, то клик на кнопку отправит данные на сервер) Обычно люди хотят `type="button"`, у которого нет поведения по умолчанию.

Но эта информация скорее актуальна для разработчиков библиотек компонентов)

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/cards.css
> +img {
это лишнее, случайно осталось видимо

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/cards.css
> +    flex-basis: content;
не очень понимаю зачем указывать flex-basis: content и ширину одновременно, flex-basis победит. Вообще размер картинки фиксирован, так что оба эти свойства ничего не делают

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/cards.css
> +h2 {
нужно перейти на класс

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/filters.css
> +.filter {
что этот селектор делает?

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/footer.css
> +footer {
есть и класс footer, и селектор по элементу footer, и они разные, и применяются к разным элементам) Сильно с толку сбивает

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/header.css
> +header {
с header та же история, что с footer

2022-03-05 06:34 UTC, alserz1 commented on public/css/components/search.css
> +    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cpath d='M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.1
есть какая-то конкретная причина инлайнить svg? С точки зрения производительности выгоднее вынести это в отдельный файл.

А ещё я бы сделал эту иконку вообще отдельной кнопкой, как на том же MDN. Некоторые люди реально кликают в такие вещи)

(извиняюсь, что в первый раз не заметил, ревью это сложно)

2022-03-05 06:34 UTC, alserz1 commented on public/css/pages/character-page.css
> +    align-items: center;
зачем? Оба элемента меняют свою позицию на flex-start

2022-03-05 06:34 UTC, alserz1 commented on public/css/pages/character-page.css
> +    background: rgb(85, 204, 68);
некоторые цвета встречаются несколько раз, например, этот цвет встречается 4 раза. Лучше такие вещи выносить в переменную и использовать переменную: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2022-03-05 06:34 UTC, alserz1 commented on public/css/pages/character-page.css
> +    font-size: 1.5em;
где-то используется `em`, где-то `rem`, хотя нигде разницы в поведении вроде не будет (но я не все места проверял). Зачем так?

2022-03-05 06:34 UTC, alserz1 commented on public/css/pages/main-page.css
> +.main__text {
пустой селектор

2022-03-05 07:55 UTC, quicksilver32 commented on public/css/components/filters.css
> +.filter {
grid-column-start убрала, а align-self надо, чтобы фильтры к верху прикрепились, если карточек много

2022-03-05 09:46 UTC, alserz1 commented on public/css/components/filters.css
> +.filter {
align-self нужен из-за того, что на родителе висит align-items: center. А зачем он на родителе, там вроде везде выравнивается в начало?

2022-03-05 11:08 UTC, quicksilver32 commented
@alserz1 поправила

2022-03-14 04:59 UTC, alserz1 commented
Извиняюсь что так долго, был в отпуске. Теперь выглядит неплохо, этот этап засчитываю. Как минимум одно замечание (про использование em/rem) закрыто, но ответа на него нет, но оно мне не сильно критично. Просто лучше так не делать)

2022-03-14 09:15 UTC, quicksilver32 commented
> Извиняюсь что так долго, был в отпуске. Теперь выглядит неплохо, этот этап засчитываю. Как минимум одно замечание (про использование em/rem) закрыто, но ответа на него нет, но оно мне не сильно критично. Просто лучше так не делать)

Спасибо большое)

2022-03-14 09:15 UTC, merged